CodeSystem: RecuperoTiposDocumentoCS
Id: tipos-documento-codesystem
Title: "Tipos de Documento"
Description:  "Listado de Tipos de Documento para Personas"
* #DNI "DOCUMENTO NACIONAL DE IDENTIDAD ARGENTINO"
* #PAS-CL "PASAPORTE CHILENO"
* #PAS-UR "PASAPORTE URUGUAYO"
* #PAS-CO "PASAPORTE COLOMBIANO"
* #PAS-BR "PASAPORTE BRASILEÑO"
* #PAS-BO "PASAPORTE BOLIVIANO"
* #PAS-EC "PASAPORTE ECUATORIANO"
* #PAS-VE "PASAPORTE VENEZOLANO"
* #PAS-US "PASAPORTE NORTEAMERICANO"